# Generated by Django 2.1.5 on 2019-02-13 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comics', '0001_initial'),
        ('people', '0002_load_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Normal'), ('O', 'Off Screen'), ('M', 'Mentioned'), ('C', 'Cameo')], default='N', max_length=1)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='comics.Installment')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Page')),
            ],
            options={
                'ordering': ['page__order'],
            },
        ),
        migrations.CreateModel(
            name='Being',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['primary_persona__name'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MugShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_x', models.FloatField()),
                ('center_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comics.SourceImage')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('GN', 'Given Name'), ('SI', 'Super Identity'), ('JJ', 'Alias')], default='GN', max_length=2)),
                ('appearances', models.ManyToManyField(related_name='characters', through='characters.Appearance', to='comics.Page')),
                ('being', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='characters.Being')),
                ('classification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='characters.Classification')),
                ('creators', models.ManyToManyField(blank=True, related_name='characters', related_query_name='persona', to='people.Entity')),
                ('mug_shot', models.ManyToManyField(blank=True, related_name='mug_shots_for', through='characters.MugShot', to='comics.SourceImage')),
                ('profile_pic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_of', to='comics.SourceImage')),
            ],
            options={
                'ordering': ['name'],
                'default_manager_name': 'display_objects',
            },
            managers=[
                ('display_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='mugshot',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Persona'),
        ),
        migrations.AddField(
            model_name='being',
            name='primary_persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='characters.Persona'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('being', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together={('installment', 'persona', 'page')},
        ),
    ]
