# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('has_cover', models.BooleanField(default=True)),
                ('paginated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Series'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('issue', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('series', 'number')]),
        ),
    ]
