# Generated by Django 2.1.7 on 2019-04-01 00:26

import django.utils.timezone
from django.db import migrations, models

import comics.fields
import comics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericImage',
            fields=[
                ('id', comics.fields.ShortUUIDField(default=comics.fields.ShortUUIDField.gen, max_length=12, primary_key=True, serialize=False)),
                ('scaled', models.ImageField(height_field='scaled_height', upload_to=comics.models.get_ci_loc, width_field='scaled_width')),
                ('scaled_width', models.PositiveIntegerField()),
                ('scaled_height', models.PositiveIntegerField()),
                ('src', models.ImageField(upload_to=comics.models.get_ci_src_loc)),
                ('x1', models.PositiveIntegerField(default=0)),
                ('y1', models.PositiveIntegerField(default=0)),
                ('x2', models.PositiveIntegerField(default=0)),
                ('y2', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            bases=(comics.models.ImageFileMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(default=0, help_text='1-indexed default ordering within containing Series.')),
                ('number', models.DecimalField(blank=True, decimal_places=5, help_text='Numeric designation, not including common label.', max_digits=10, null=True)),
                ('title', models.CharField(blank=True, help_text='In place of, or in addition to, a Number.', max_length=200)),
                ('synopsis', models.TextField(blank=True)),
                ('release_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_cover', models.BooleanField(default=True, help_text='Treat the first page (by order) as the cover.')),
                ('archive', models.FileField(editable=False, null=True, upload_to=comics.models.gen_arch_loc)),
            ],
            options={
                'ordering': ['ordinal'],
            },
            bases=(comics.models.ImageFileMixin, comics.models.ThreadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InstallmentLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=20, unique=True)),
                ('is_strip', models.BooleanField(default=False)),
                ('flip_direction', models.CharField(choices=[('LTR', 'Left-to-Right'), ('RTL', 'Right-to-Left')], default='LTR', max_length=3)),
                ('installment_label', models.ForeignKey(default=comics.models.InstallmentLabel.get_default_label, help_text='Numbers will be prefixed with this value when displayed.', on_delete=django.db.models.deletion.PROTECT, to='comics.InstallmentLabel')),
            ],
            options={
                'verbose_name_plural': 'series',
            },
            bases=(comics.models.ThreadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(height_field='file_height', upload_to=comics.models.gen_src_loc, width_field='file_width')),
                ('file_width', models.PositiveIntegerField()),
                ('file_height', models.PositiveIntegerField()),
                ('original_name', models.CharField(max_length=260)),
            ],
            bases=(comics.models.ImageFileMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('F', 'Freeform'), ('S', 'Story'), ('V', 'Volume'), ('A', 'Arc')], default='F', max_length=1)),
                ('issue_based', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('begin_page', models.PositiveSmallIntegerField(default=0)),
                ('end_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comics.Installment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Thread')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('sourceimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comics.SourceImage')),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False, help_text='The 0-indexed ordering within parent Installment.')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('comics.sourceimage',),
        ),
        migrations.AddField(
            model_name='thread',
            name='installments',
            field=models.ManyToManyField(through='comics.ThreadSequence', to='comics.Installment'),
        ),
        migrations.AddField(
            model_name='installment',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='comics.Series'),
        ),
        migrations.AddField(
            model_name='page',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='comics.Installment'),
        ),
        migrations.AddField(
            model_name='installment',
            name='page',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strip', to='comics.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('series', 'number', 'title')},
        ),
    ]
