# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 19:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import comics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('has_cover', models.BooleanField(default=True)),
                ('flip_direction', models.CharField(choices=[('LTR', 'Left-to-Right'), ('RTL', 'Right-to-Left')], default='LTR', max_length=3)),
            ],
            options={
                'ordering': ['series', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(height_field='file_height', upload_to=comics.models.gen_src_loc, width_field='file_width')),
                ('file_width', models.PositiveIntegerField()),
                ('file_height', models.PositiveIntegerField()),
                ('original_name', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('F', 'Freeform'), ('S', 'Story'), (('V',), 'Volume'), (('A',), 'Arc')], default='F', max_length=1)),
                ('issue_based', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('begin_page', models.PositiveSmallIntegerField(default=0)),
                ('end_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comics.Installment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Thread')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('sourceimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comics.SourceImage')),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False, help_text='The 0-indexed ordering within parent Installment.')),
                ('number', models.PositiveSmallIntegerField(help_text="Essentially, the page 'name'.")),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('comics.sourceimage',),
        ),
        migrations.AddField(
            model_name='thread',
            name='installments',
            field=models.ManyToManyField(through='comics.ThreadSequence', to='comics.Installment'),
        ),
        migrations.AddField(
            model_name='installment',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Series'),
        ),
        migrations.AddField(
            model_name='page',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='comics.Installment'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together=set([('series', 'number')]),
        ),
    ]
