# Generated by Django 2.1.5 on 2019-02-18 20:00

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Normal'), ('O', 'Off Screen'), ('M', 'Mentioned')], default='N', help_text='Whether visible on the page, or otherwise present.', max_length=1)),
                ('is_spoiler', models.BooleanField(default=False, help_text='Obscure this appearance in certain contexts.')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='comics.Installment')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Page')),
            ],
            options={
                'ordering': ['page__order'],
            },
        ),
        migrations.CreateModel(
            name='Being',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='One-to-several paragraphs, but not a full wiki entry.')),
            ],
            options={
                'ordering': ['primary_persona__name'],
            },
        ),
        migrations.CreateModel(
            name='BeingUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('being', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='metadata.Being')),
            ],
            options={
                'verbose_name': 'url',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['working_name'],
            },
        ),
        migrations.CreateModel(
            name='EntityUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='metadata.Entity')),
            ],
            options={
                'verbose_name': 'url',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name, without any additional designation.', max_length=200)),
                ('type', models.CharField(choices=[('GN', 'Given Name'), ('SI', 'Super Identity'), ('JJ', 'Alias')], default='GN', help_text='Alter ego type or purpose.', max_length=2)),
                ('appearances', models.ManyToManyField(related_name='characters', through='metadata.Appearance', to='comics.Page')),
                ('being', models.ForeignKey(blank=True, help_text='Singular underlying entity.', on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='metadata.Being')),
                ('classification', models.ForeignKey(default=1, help_text='Alter ego manner of being. (See: Shazam)', on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='metadata.Classification')),
                ('creators', models.ManyToManyField(blank=True, related_name='characters', related_query_name='persona', to='metadata.Entity')),
                ('profile_pic', models.OneToOneField(blank=True, help_text='Full body portrait.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_of', to='comics.SourceImage')),
            ],
            options={
                'ordering': ['name'],
                'default_manager_name': 'display_objects',
            },
            managers=[
                ('display_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Entity'),
        ),
        migrations.AddField(
            model_name='credit',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Role'),
        ),
        migrations.AddField(
            model_name='being',
            name='primary_persona',
            field=models.OneToOneField(blank=True, help_text='What this being is primarily known as.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='metadata.Persona'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('being', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together={('object_id', 'content_type', 'entity', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together={('installment', 'persona', 'page')},
        ),
    ]
