# Generated by Django 2.1.5 on 2019-02-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['working_name'],
            },
        ),
        migrations.CreateModel(
            name='EntityUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='people.Entity')),
            ],
            options={
                'verbose_name': 'url',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Entity'),
        ),
        migrations.AddField(
            model_name='credit',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together={('object_id', 'content_type', 'entity', 'role')},
        ),
    ]
